### ISSUE TITLE
Not able to pull in submodules (no permissions)

### ISSUE THREAD

**Issue by bgatten** [kyk0910/sampling-based-planners#3]
git submodule update --init returns 
"fatal: clone of 'git@github.com:kyk0910/OpenCV-YAMLHelper.git' into submodule path '/home/ben/planning/sampling-based-planners/examples/external/OpenCV-YAMLHelper' failed"

**Comment by medalotte** [comment]
@bgatten thanks! I've just fixed the submodule url prefix from `git@github.com:` to `https://`.
Please try the following commands.

```shell
$ git pull origin master
$ git submodule sync
$ git submodule update --init
```
